linters:
  disable-all: true
  enable:
    - gofmt
    - revive
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - vet
    - vetshadow
    - errcheck

run:

  # timeout for analysis
  timeout: 10m

  skip-dirs:
    - hack
    - docs
    - test
    - vendor

issues:

  # List of regexps of issue texts to exclude
  exclude:
    - "comment on"
    - "error should be the last"
    - "should have comment"
