// Code generated by capnpc-go. DO NOT EDIT.

package vncapnp

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type VnObjectItemsGetResponseHeader struct{ capnp.Struct }

// VnObjectItemsGetResponseHeader_TypeID is the unique identifier for the type VnObjectItemsGetResponseHeader.
const VnObjectItemsGetResponseHeader_TypeID = 0x85032dcfe77493da

func NewVnObjectItemsGetResponseHeader(s *capnp.Segment) (VnObjectItemsGetResponseHeader, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2})
	return VnObjectItemsGetResponseHeader{st}, err
}

func NewRootVnObjectItemsGetResponseHeader(s *capnp.Segment) (VnObjectItemsGetResponseHeader, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2})
	return VnObjectItemsGetResponseHeader{st}, err
}

func ReadRootVnObjectItemsGetResponseHeader(msg *capnp.Message) (VnObjectItemsGetResponseHeader, error) {
	root, err := msg.RootPtr()
	return VnObjectItemsGetResponseHeader{root.Struct()}, err
}

func (s VnObjectItemsGetResponseHeader) String() string {
	str, _ := text.Marshal(0x85032dcfe77493da, s.Struct)
	return str
}

func (s VnObjectItemsGetResponseHeader) Marker() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s VnObjectItemsGetResponseHeader) HasMarker() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetResponseHeader) MarkerBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s VnObjectItemsGetResponseHeader) SetMarker(v string) error {
	return s.Struct.SetText(0, v)
}

func (s VnObjectItemsGetResponseHeader) ScanState() (VnObjectItemsScanCookie, error) {
	p, err := s.Struct.Ptr(1)
	return VnObjectItemsScanCookie{Struct: p.Struct()}, err
}

func (s VnObjectItemsGetResponseHeader) HasScanState() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetResponseHeader) SetScanState(v VnObjectItemsScanCookie) error {
	return s.Struct.SetPtr(1, v.Struct.ToPtr())
}

// NewScanState sets the scanState field to a newly
// allocated VnObjectItemsScanCookie struct, preferring placement in s's segment.
func (s VnObjectItemsGetResponseHeader) NewScanState() (VnObjectItemsScanCookie, error) {
	ss, err := NewVnObjectItemsScanCookie(s.Struct.Segment())
	if err != nil {
		return VnObjectItemsScanCookie{}, err
	}
	err = s.Struct.SetPtr(1, ss.Struct.ToPtr())
	return ss, err
}

func (s VnObjectItemsGetResponseHeader) HasMore() bool {
	return s.Struct.Bit(0)
}

func (s VnObjectItemsGetResponseHeader) SetHasMore(v bool) {
	s.Struct.SetBit(0, v)
}

func (s VnObjectItemsGetResponseHeader) NumItems() uint64 {
	return s.Struct.Uint64(8)
}

func (s VnObjectItemsGetResponseHeader) SetNumItems(v uint64) {
	s.Struct.SetUint64(8, v)
}

func (s VnObjectItemsGetResponseHeader) NumKeys() uint64 {
	return s.Struct.Uint64(16)
}

func (s VnObjectItemsGetResponseHeader) SetNumKeys(v uint64) {
	s.Struct.SetUint64(16, v)
}

func (s VnObjectItemsGetResponseHeader) NumValues() uint64 {
	return s.Struct.Uint64(24)
}

func (s VnObjectItemsGetResponseHeader) SetNumValues(v uint64) {
	s.Struct.SetUint64(24, v)
}

// VnObjectItemsGetResponseHeader_List is a list of VnObjectItemsGetResponseHeader.
type VnObjectItemsGetResponseHeader_List struct{ capnp.List }

// NewVnObjectItemsGetResponseHeader creates a new list of VnObjectItemsGetResponseHeader.
func NewVnObjectItemsGetResponseHeader_List(s *capnp.Segment, sz int32) (VnObjectItemsGetResponseHeader_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2}, sz)
	return VnObjectItemsGetResponseHeader_List{l}, err
}

func (s VnObjectItemsGetResponseHeader_List) At(i int) VnObjectItemsGetResponseHeader {
	return VnObjectItemsGetResponseHeader{s.List.Struct(i)}
}

func (s VnObjectItemsGetResponseHeader_List) Set(i int, v VnObjectItemsGetResponseHeader) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectItemsGetResponseHeader_List) String() string {
	str, _ := text.MarshalList(0x85032dcfe77493da, s.List)
	return str
}

// VnObjectItemsGetResponseHeader_Promise is a wrapper for a VnObjectItemsGetResponseHeader promised by a client call.
type VnObjectItemsGetResponseHeader_Promise struct{ *capnp.Pipeline }

func (p VnObjectItemsGetResponseHeader_Promise) Struct() (VnObjectItemsGetResponseHeader, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectItemsGetResponseHeader{s}, err
}

func (p VnObjectItemsGetResponseHeader_Promise) ScanState() VnObjectItemsScanCookie_Promise {
	return VnObjectItemsScanCookie_Promise{Pipeline: p.Pipeline.GetPipeline(1)}
}

type VnObjectItemsGetMappedKeyValuePair struct{ capnp.Struct }

// VnObjectItemsGetMappedKeyValuePair_TypeID is the unique identifier for the type VnObjectItemsGetMappedKeyValuePair.
const VnObjectItemsGetMappedKeyValuePair_TypeID = 0xd26f89592f5fc95f

func NewVnObjectItemsGetMappedKeyValuePair(s *capnp.Segment) (VnObjectItemsGetMappedKeyValuePair, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return VnObjectItemsGetMappedKeyValuePair{st}, err
}

func NewRootVnObjectItemsGetMappedKeyValuePair(s *capnp.Segment) (VnObjectItemsGetMappedKeyValuePair, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return VnObjectItemsGetMappedKeyValuePair{st}, err
}

func ReadRootVnObjectItemsGetMappedKeyValuePair(msg *capnp.Message) (VnObjectItemsGetMappedKeyValuePair, error) {
	root, err := msg.RootPtr()
	return VnObjectItemsGetMappedKeyValuePair{root.Struct()}, err
}

func (s VnObjectItemsGetMappedKeyValuePair) String() string {
	str, _ := text.Marshal(0xd26f89592f5fc95f, s.Struct)
	return str
}

func (s VnObjectItemsGetMappedKeyValuePair) KeyMapIndex() uint64 {
	return s.Struct.Uint64(0)
}

func (s VnObjectItemsGetMappedKeyValuePair) SetKeyMapIndex(v uint64) {
	s.Struct.SetUint64(0, v)
}

func (s VnObjectItemsGetMappedKeyValuePair) ValueMapIndex() uint64 {
	return s.Struct.Uint64(8)
}

func (s VnObjectItemsGetMappedKeyValuePair) SetValueMapIndex(v uint64) {
	s.Struct.SetUint64(8, v)
}

// VnObjectItemsGetMappedKeyValuePair_List is a list of VnObjectItemsGetMappedKeyValuePair.
type VnObjectItemsGetMappedKeyValuePair_List struct{ capnp.List }

// NewVnObjectItemsGetMappedKeyValuePair creates a new list of VnObjectItemsGetMappedKeyValuePair.
func NewVnObjectItemsGetMappedKeyValuePair_List(s *capnp.Segment, sz int32) (VnObjectItemsGetMappedKeyValuePair_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return VnObjectItemsGetMappedKeyValuePair_List{l}, err
}

func (s VnObjectItemsGetMappedKeyValuePair_List) At(i int) VnObjectItemsGetMappedKeyValuePair {
	return VnObjectItemsGetMappedKeyValuePair{s.List.Struct(i)}
}

func (s VnObjectItemsGetMappedKeyValuePair_List) Set(i int, v VnObjectItemsGetMappedKeyValuePair) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectItemsGetMappedKeyValuePair_List) String() string {
	str, _ := text.MarshalList(0xd26f89592f5fc95f, s.List)
	return str
}

// VnObjectItemsGetMappedKeyValuePair_Promise is a wrapper for a VnObjectItemsGetMappedKeyValuePair promised by a client call.
type VnObjectItemsGetMappedKeyValuePair_Promise struct{ *capnp.Pipeline }

func (p VnObjectItemsGetMappedKeyValuePair_Promise) Struct() (VnObjectItemsGetMappedKeyValuePair, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectItemsGetMappedKeyValuePair{s}, err
}

type VnObjectItemsGetItem struct{ capnp.Struct }

// VnObjectItemsGetItem_TypeID is the unique identifier for the type VnObjectItemsGetItem.
const VnObjectItemsGetItem_TypeID = 0xeacf121c1705f7c7

func NewVnObjectItemsGetItem(s *capnp.Segment) (VnObjectItemsGetItem, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VnObjectItemsGetItem{st}, err
}

func NewRootVnObjectItemsGetItem(s *capnp.Segment) (VnObjectItemsGetItem, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VnObjectItemsGetItem{st}, err
}

func ReadRootVnObjectItemsGetItem(msg *capnp.Message) (VnObjectItemsGetItem, error) {
	root, err := msg.RootPtr()
	return VnObjectItemsGetItem{root.Struct()}, err
}

func (s VnObjectItemsGetItem) String() string {
	str, _ := text.Marshal(0xeacf121c1705f7c7, s.Struct)
	return str
}

func (s VnObjectItemsGetItem) Name() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s VnObjectItemsGetItem) HasName() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetItem) NameBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s VnObjectItemsGetItem) SetName(v string) error {
	return s.Struct.SetText(0, v)
}

func (s VnObjectItemsGetItem) Attrs() (VnObjectItemsGetMappedKeyValuePair_List, error) {
	p, err := s.Struct.Ptr(1)
	return VnObjectItemsGetMappedKeyValuePair_List{List: p.List()}, err
}

func (s VnObjectItemsGetItem) HasAttrs() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetItem) SetAttrs(v VnObjectItemsGetMappedKeyValuePair_List) error {
	return s.Struct.SetPtr(1, v.List.ToPtr())
}

// NewAttrs sets the attrs field to a newly
// allocated VnObjectItemsGetMappedKeyValuePair_List, preferring placement in s's segment.
func (s VnObjectItemsGetItem) NewAttrs(n int32) (VnObjectItemsGetMappedKeyValuePair_List, error) {
	l, err := NewVnObjectItemsGetMappedKeyValuePair_List(s.Struct.Segment(), n)
	if err != nil {
		return VnObjectItemsGetMappedKeyValuePair_List{}, err
	}
	err = s.Struct.SetPtr(1, l.List.ToPtr())
	return l, err
}

// VnObjectItemsGetItem_List is a list of VnObjectItemsGetItem.
type VnObjectItemsGetItem_List struct{ capnp.List }

// NewVnObjectItemsGetItem creates a new list of VnObjectItemsGetItem.
func NewVnObjectItemsGetItem_List(s *capnp.Segment, sz int32) (VnObjectItemsGetItem_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return VnObjectItemsGetItem_List{l}, err
}

func (s VnObjectItemsGetItem_List) At(i int) VnObjectItemsGetItem {
	return VnObjectItemsGetItem{s.List.Struct(i)}
}

func (s VnObjectItemsGetItem_List) Set(i int, v VnObjectItemsGetItem) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectItemsGetItem_List) String() string {
	str, _ := text.MarshalList(0xeacf121c1705f7c7, s.List)
	return str
}

// VnObjectItemsGetItem_Promise is a wrapper for a VnObjectItemsGetItem promised by a client call.
type VnObjectItemsGetItem_Promise struct{ *capnp.Pipeline }

func (p VnObjectItemsGetItem_Promise) Struct() (VnObjectItemsGetItem, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectItemsGetItem{s}, err
}

type VnObjectItemsGetItemPtr struct{ capnp.Struct }

// VnObjectItemsGetItemPtr_TypeID is the unique identifier for the type VnObjectItemsGetItemPtr.
const VnObjectItemsGetItemPtr_TypeID = 0xf020cf2eadb0357c

func NewVnObjectItemsGetItemPtr(s *capnp.Segment) (VnObjectItemsGetItemPtr, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectItemsGetItemPtr{st}, err
}

func NewRootVnObjectItemsGetItemPtr(s *capnp.Segment) (VnObjectItemsGetItemPtr, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectItemsGetItemPtr{st}, err
}

func ReadRootVnObjectItemsGetItemPtr(msg *capnp.Message) (VnObjectItemsGetItemPtr, error) {
	root, err := msg.RootPtr()
	return VnObjectItemsGetItemPtr{root.Struct()}, err
}

func (s VnObjectItemsGetItemPtr) String() string {
	str, _ := text.Marshal(0xf020cf2eadb0357c, s.Struct)
	return str
}

func (s VnObjectItemsGetItemPtr) Item() (VnObjectItemsGetItem, error) {
	p, err := s.Struct.Ptr(0)
	return VnObjectItemsGetItem{Struct: p.Struct()}, err
}

func (s VnObjectItemsGetItemPtr) HasItem() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetItemPtr) SetItem(v VnObjectItemsGetItem) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewItem sets the item field to a newly
// allocated VnObjectItemsGetItem struct, preferring placement in s's segment.
func (s VnObjectItemsGetItemPtr) NewItem() (VnObjectItemsGetItem, error) {
	ss, err := NewVnObjectItemsGetItem(s.Struct.Segment())
	if err != nil {
		return VnObjectItemsGetItem{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// VnObjectItemsGetItemPtr_List is a list of VnObjectItemsGetItemPtr.
type VnObjectItemsGetItemPtr_List struct{ capnp.List }

// NewVnObjectItemsGetItemPtr creates a new list of VnObjectItemsGetItemPtr.
func NewVnObjectItemsGetItemPtr_List(s *capnp.Segment, sz int32) (VnObjectItemsGetItemPtr_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return VnObjectItemsGetItemPtr_List{l}, err
}

func (s VnObjectItemsGetItemPtr_List) At(i int) VnObjectItemsGetItemPtr {
	return VnObjectItemsGetItemPtr{s.List.Struct(i)}
}

func (s VnObjectItemsGetItemPtr_List) Set(i int, v VnObjectItemsGetItemPtr) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectItemsGetItemPtr_List) String() string {
	str, _ := text.MarshalList(0xf020cf2eadb0357c, s.List)
	return str
}

// VnObjectItemsGetItemPtr_Promise is a wrapper for a VnObjectItemsGetItemPtr promised by a client call.
type VnObjectItemsGetItemPtr_Promise struct{ *capnp.Pipeline }

func (p VnObjectItemsGetItemPtr_Promise) Struct() (VnObjectItemsGetItemPtr, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectItemsGetItemPtr{s}, err
}

func (p VnObjectItemsGetItemPtr_Promise) Item() VnObjectItemsGetItem_Promise {
	return VnObjectItemsGetItem_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type VnObjectItemsGetResponseDataPayload struct{ capnp.Struct }

// VnObjectItemsGetResponseDataPayload_TypeID is the unique identifier for the type VnObjectItemsGetResponseDataPayload.
const VnObjectItemsGetResponseDataPayload_TypeID = 0xbb85e91da7f4c0a3

func NewVnObjectItemsGetResponseDataPayload(s *capnp.Segment) (VnObjectItemsGetResponseDataPayload, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectItemsGetResponseDataPayload{st}, err
}

func NewRootVnObjectItemsGetResponseDataPayload(s *capnp.Segment) (VnObjectItemsGetResponseDataPayload, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectItemsGetResponseDataPayload{st}, err
}

func ReadRootVnObjectItemsGetResponseDataPayload(msg *capnp.Message) (VnObjectItemsGetResponseDataPayload, error) {
	root, err := msg.RootPtr()
	return VnObjectItemsGetResponseDataPayload{root.Struct()}, err
}

func (s VnObjectItemsGetResponseDataPayload) String() string {
	str, _ := text.Marshal(0xbb85e91da7f4c0a3, s.Struct)
	return str
}

func (s VnObjectItemsGetResponseDataPayload) ValueMap() (VnObjectAttributeValueMap, error) {
	p, err := s.Struct.Ptr(0)
	return VnObjectAttributeValueMap{Struct: p.Struct()}, err
}

func (s VnObjectItemsGetResponseDataPayload) HasValueMap() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetResponseDataPayload) SetValueMap(v VnObjectAttributeValueMap) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewValueMap sets the valueMap field to a newly
// allocated VnObjectAttributeValueMap struct, preferring placement in s's segment.
func (s VnObjectItemsGetResponseDataPayload) NewValueMap() (VnObjectAttributeValueMap, error) {
	ss, err := NewVnObjectAttributeValueMap(s.Struct.Segment())
	if err != nil {
		return VnObjectAttributeValueMap{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// VnObjectItemsGetResponseDataPayload_List is a list of VnObjectItemsGetResponseDataPayload.
type VnObjectItemsGetResponseDataPayload_List struct{ capnp.List }

// NewVnObjectItemsGetResponseDataPayload creates a new list of VnObjectItemsGetResponseDataPayload.
func NewVnObjectItemsGetResponseDataPayload_List(s *capnp.Segment, sz int32) (VnObjectItemsGetResponseDataPayload_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return VnObjectItemsGetResponseDataPayload_List{l}, err
}

func (s VnObjectItemsGetResponseDataPayload_List) At(i int) VnObjectItemsGetResponseDataPayload {
	return VnObjectItemsGetResponseDataPayload{s.List.Struct(i)}
}

func (s VnObjectItemsGetResponseDataPayload_List) Set(i int, v VnObjectItemsGetResponseDataPayload) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectItemsGetResponseDataPayload_List) String() string {
	str, _ := text.MarshalList(0xbb85e91da7f4c0a3, s.List)
	return str
}

// VnObjectItemsGetResponseDataPayload_Promise is a wrapper for a VnObjectItemsGetResponseDataPayload promised by a client call.
type VnObjectItemsGetResponseDataPayload_Promise struct{ *capnp.Pipeline }

func (p VnObjectItemsGetResponseDataPayload_Promise) Struct() (VnObjectItemsGetResponseDataPayload, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectItemsGetResponseDataPayload{s}, err
}

func (p VnObjectItemsGetResponseDataPayload_Promise) ValueMap() VnObjectAttributeValueMap_Promise {
	return VnObjectAttributeValueMap_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type VnObjectItemsGetResponseMetadataPayload struct{ capnp.Struct }

// VnObjectItemsGetResponseMetadataPayload_TypeID is the unique identifier for the type VnObjectItemsGetResponseMetadataPayload.
const VnObjectItemsGetResponseMetadataPayload_TypeID = 0xb4008849dd7a3304

func NewVnObjectItemsGetResponseMetadataPayload(s *capnp.Segment) (VnObjectItemsGetResponseMetadataPayload, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return VnObjectItemsGetResponseMetadataPayload{st}, err
}

func NewRootVnObjectItemsGetResponseMetadataPayload(s *capnp.Segment) (VnObjectItemsGetResponseMetadataPayload, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return VnObjectItemsGetResponseMetadataPayload{st}, err
}

func ReadRootVnObjectItemsGetResponseMetadataPayload(msg *capnp.Message) (VnObjectItemsGetResponseMetadataPayload, error) {
	root, err := msg.RootPtr()
	return VnObjectItemsGetResponseMetadataPayload{root.Struct()}, err
}

func (s VnObjectItemsGetResponseMetadataPayload) String() string {
	str, _ := text.Marshal(0xb4008849dd7a3304, s.Struct)
	return str
}

func (s VnObjectItemsGetResponseMetadataPayload) ValueMap() (VnObjectAttributeValueMap, error) {
	p, err := s.Struct.Ptr(0)
	return VnObjectAttributeValueMap{Struct: p.Struct()}, err
}

func (s VnObjectItemsGetResponseMetadataPayload) HasValueMap() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetResponseMetadataPayload) SetValueMap(v VnObjectAttributeValueMap) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewValueMap sets the valueMap field to a newly
// allocated VnObjectAttributeValueMap struct, preferring placement in s's segment.
func (s VnObjectItemsGetResponseMetadataPayload) NewValueMap() (VnObjectAttributeValueMap, error) {
	ss, err := NewVnObjectAttributeValueMap(s.Struct.Segment())
	if err != nil {
		return VnObjectAttributeValueMap{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

func (s VnObjectItemsGetResponseMetadataPayload) KeyMap() (VnObjectAttributeKeyMap, error) {
	p, err := s.Struct.Ptr(1)
	return VnObjectAttributeKeyMap{Struct: p.Struct()}, err
}

func (s VnObjectItemsGetResponseMetadataPayload) HasKeyMap() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetResponseMetadataPayload) SetKeyMap(v VnObjectAttributeKeyMap) error {
	return s.Struct.SetPtr(1, v.Struct.ToPtr())
}

// NewKeyMap sets the keyMap field to a newly
// allocated VnObjectAttributeKeyMap struct, preferring placement in s's segment.
func (s VnObjectItemsGetResponseMetadataPayload) NewKeyMap() (VnObjectAttributeKeyMap, error) {
	ss, err := NewVnObjectAttributeKeyMap(s.Struct.Segment())
	if err != nil {
		return VnObjectAttributeKeyMap{}, err
	}
	err = s.Struct.SetPtr(1, ss.Struct.ToPtr())
	return ss, err
}

func (s VnObjectItemsGetResponseMetadataPayload) Items() (VnObjectItemsGetItemPtr_List, error) {
	p, err := s.Struct.Ptr(2)
	return VnObjectItemsGetItemPtr_List{List: p.List()}, err
}

func (s VnObjectItemsGetResponseMetadataPayload) HasItems() bool {
	p, err := s.Struct.Ptr(2)
	return p.IsValid() || err != nil
}

func (s VnObjectItemsGetResponseMetadataPayload) SetItems(v VnObjectItemsGetItemPtr_List) error {
	return s.Struct.SetPtr(2, v.List.ToPtr())
}

// NewItems sets the items field to a newly
// allocated VnObjectItemsGetItemPtr_List, preferring placement in s's segment.
func (s VnObjectItemsGetResponseMetadataPayload) NewItems(n int32) (VnObjectItemsGetItemPtr_List, error) {
	l, err := NewVnObjectItemsGetItemPtr_List(s.Struct.Segment(), n)
	if err != nil {
		return VnObjectItemsGetItemPtr_List{}, err
	}
	err = s.Struct.SetPtr(2, l.List.ToPtr())
	return l, err
}

// VnObjectItemsGetResponseMetadataPayload_List is a list of VnObjectItemsGetResponseMetadataPayload.
type VnObjectItemsGetResponseMetadataPayload_List struct{ capnp.List }

// NewVnObjectItemsGetResponseMetadataPayload creates a new list of VnObjectItemsGetResponseMetadataPayload.
func NewVnObjectItemsGetResponseMetadataPayload_List(s *capnp.Segment, sz int32) (VnObjectItemsGetResponseMetadataPayload_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return VnObjectItemsGetResponseMetadataPayload_List{l}, err
}

func (s VnObjectItemsGetResponseMetadataPayload_List) At(i int) VnObjectItemsGetResponseMetadataPayload {
	return VnObjectItemsGetResponseMetadataPayload{s.List.Struct(i)}
}

func (s VnObjectItemsGetResponseMetadataPayload_List) Set(i int, v VnObjectItemsGetResponseMetadataPayload) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectItemsGetResponseMetadataPayload_List) String() string {
	str, _ := text.MarshalList(0xb4008849dd7a3304, s.List)
	return str
}

// VnObjectItemsGetResponseMetadataPayload_Promise is a wrapper for a VnObjectItemsGetResponseMetadataPayload promised by a client call.
type VnObjectItemsGetResponseMetadataPayload_Promise struct{ *capnp.Pipeline }

func (p VnObjectItemsGetResponseMetadataPayload_Promise) Struct() (VnObjectItemsGetResponseMetadataPayload, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectItemsGetResponseMetadataPayload{s}, err
}

func (p VnObjectItemsGetResponseMetadataPayload_Promise) ValueMap() VnObjectAttributeValueMap_Promise {
	return VnObjectAttributeValueMap_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

func (p VnObjectItemsGetResponseMetadataPayload_Promise) KeyMap() VnObjectAttributeKeyMap_Promise {
	return VnObjectAttributeKeyMap_Promise{Pipeline: p.Pipeline.GetPipeline(1)}
}

const schema_dfe00955984fcb17 = "x\xda\xac\x94OhcU\x14\xc6\xcfw\xefK^\"" +
	"\xd1\xe6\x99@\xbb\xb0D\xc5EU\xda4m\xddT!" +
	"\"-6\xad\xa1\xb9\xd5V\\\xd5\xdb\xe4Bk\x9b\x97" +
	"\xf0\xf2\xaaF\x84\x82X\xd0\x85\xba\xa8\x0b\x05\x85\xa2\x88" +
	"\xad\xb6h\xa1\x82\xe0\xc2n\xa4T\x17\x05]\xb5 \xba" +
	"\x98a\xfe\xacf``f\x16\xc3\x1b\xee\xcb\xdf)3" +
	"\x0ct\xba\xbb\xef\xdc\x8f\xfb~\xdfw\xce\xbd\xfd\xf3\xec" +
	"E\x96\x0aL\x86\x89\xc4R \xe8\x1d\xaf\xb9\x17\x0e{" +
	"\xf9*\x89\x14\x0c\xaf\xf3\xaf\xc9/\xa6\xc3\xff\xffG\x01" +
	"f\x12\x0d~b|\xc0b;\x86^n\x1b\xaf\x83\xf0" +
	"\xbb1\xf8\xde\xbf\x99\x8fv\xad\x14\xda\xb4\\\x0b\x02\xc1" +
	"?Y,\x154\x89b\xbd\xc1\x9f\x08\xde\xb7{\xd7\xbe" +
	"\xef\xbe\xb4\xfa\x1b\xdd)\x86\x16\x1f\x05\x7f`1\x98Z" +
	"|+\x98&x\xb3\x07\xb3\xc97>.\xfd\xad1X" +
	"K\xed\xff\xfa\x09\xf3\x1b\x16\xcb\xf8\xe2Q\xf3\x1d\x82\xb7" +
	"\x7f=\xd0\xf9\xd8\xa3\x87\x97O\x9c\xec#o\x9a\x03," +
	"v\xe0\x8b\xff\xf0\xc5\xef?\xf7\xf3v\xdf\xe1\xe3W\xee" +
	"\x86\x91\x0a\x8d\xb3\xd8tH\x8bE(M\x17\xbd\xbc," +
	"\xdb\xe5\xa4]\x0a\x17T2_*\x16Kvr\xc6\x9e" +
	"\x9c{K\xe5\xdd\x8c\xab\x8a\x95\x97\x95;\xa5*\xe5\x92" +
	"]Q}\xbev\xf8^\xdbcJ\x16\x94C9@t" +
	"q\x83\xc8\x00\x91\xf5\xe50\x91\xf8\x9cC\xac3X@" +
	"\x1c\xba\xf8\xf5\x14\x91\xf8\x8aCl0\x80\xc5\xc1\x88\xac" +
	"\xef^\"\x12\xeb\x1cb\x8b\xc1\xe2\x88\x83\x13Y\x9b\xe3" +
	"Db\x83C\xec2X\x06\x8b\xc3 \xb2v\xb4r\x8b" +
	"C\xfc\xca`\x05x\x1c\x01\"\xeb\x17}\xe4.\x87\xd8" +
	"cH\x17\xa5\xb3\xa8\x1cD\x88!B\xf0*yi\xbf" +
	"\xeaJ\x97\xa0\x10\xf5\xde\\\xdb\xff\xb1;\xc4>$\x02" +
	"\xa2\x84\x95yY\xc9\x96\x1c\x05\x10\x03\x08\x9e\xbd\\\xf4" +
	"\x9d\x11\x11\xc2\xc4\x10&\xac\xd8\xcb\xc5\x09U\xad4\xbe" +
	"\xb5fF.-+B\xab\xd6\x08\xf2\xa1\x07\x0e2\xab" +
	"\\Y\x90\xae\xcc\xc9\xeaRI\x16\xc8\x8f4\xd2\x8ct" +
	"T\x872\xc2!rm\x91fu\xcec\x1c\xe25\x06" +
	"\x8b\xd53\x15\x03D\xe2\x15\x0e1\xcf\xe0\xbd\xad\x81\xb3" +
	"\xb2\xac}E\xbd\x9b\xcf\x1e\x9d\xff\xf4\xf8\xdc\xd5z\x0a" +
	"\xe9EU\xcd\xca2\xa2^\xcf\x8d\xe7\x9f\xdc\xf9g\xe8" +
	"\xb3\xfaFbA\xc3\xe1\x11B\x8e\x03\xd1\xd6l\x11t" +
	"\xf1\x0c\xc7g\xa4\xe6\xb8C[\xd6\x86\x8d\xa6\xe1\x87\xb5" +
	"\xe1\x08\x87\xe8\xba\x9f\x8d3\xc0\xc9\xcarY\x15&T" +
	"\xd5op\xce\x94\x0b\x8e\xa6\x095i\x9e\x9e#\x12=" +
	"\x1cb\xa8-\xfe\x94C$\xfa9\xc4\x0b\x0c^-\xcb" +
	"\x8cMfA\xbd\xdb\x9c\x8f&x\"c\xb7\xd7\x1b\xc8" +
	"\xe6i\x91\x13\xfe\xe2\x04\xe43D\xe2)\x0e\xd1\xdf\x06" +
	"\xd9;P'\x1fa\xe8\xb0eQ5nHB\xba\xae" +
	"\xd3\xd6\xe4\xe6\xd3t\xa2\xc9\xa1S\xa7\xea\x13\xbaNm" +
	"\x94\xdb:\xab1C\x1c\"\xce\xd0\xa1'\x0d\xd1\xd6S" +
	"Wk\xe9\xed\x00\x00\x00\xff\xff\xd9q\x94\x02"

func init() {
	schemas.Register(schema_dfe00955984fcb17,
		0x85032dcfe77493da,
		0xb4008849dd7a3304,
		0xbb85e91da7f4c0a3,
		0xd26f89592f5fc95f,
		0xeacf121c1705f7c7,
		0xf020cf2eadb0357c)
}
