// Code generated by capnpc-go. DO NOT EDIT.

package vncapnp

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type VnObjectAttributeValuePtr struct{ capnp.Struct }

// VnObjectAttributeValuePtr_TypeID is the unique identifier for the type VnObjectAttributeValuePtr.
const VnObjectAttributeValuePtr_TypeID = 0xd5b5408ea84873aa

func NewVnObjectAttributeValuePtr(s *capnp.Segment) (VnObjectAttributeValuePtr, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectAttributeValuePtr{st}, err
}

func NewRootVnObjectAttributeValuePtr(s *capnp.Segment) (VnObjectAttributeValuePtr, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectAttributeValuePtr{st}, err
}

func ReadRootVnObjectAttributeValuePtr(msg *capnp.Message) (VnObjectAttributeValuePtr, error) {
	root, err := msg.RootPtr()
	return VnObjectAttributeValuePtr{root.Struct()}, err
}

func (s VnObjectAttributeValuePtr) String() string {
	str, _ := text.Marshal(0xd5b5408ea84873aa, s.Struct)
	return str
}

func (s VnObjectAttributeValuePtr) Value() (ExtAttrValue, error) {
	p, err := s.Struct.Ptr(0)
	return ExtAttrValue{Struct: p.Struct()}, err
}

func (s VnObjectAttributeValuePtr) HasValue() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s VnObjectAttributeValuePtr) SetValue(v ExtAttrValue) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewValue sets the value field to a newly
// allocated ExtAttrValue struct, preferring placement in s's segment.
func (s VnObjectAttributeValuePtr) NewValue() (ExtAttrValue, error) {
	ss, err := NewExtAttrValue(s.Struct.Segment())
	if err != nil {
		return ExtAttrValue{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// VnObjectAttributeValuePtr_List is a list of VnObjectAttributeValuePtr.
type VnObjectAttributeValuePtr_List struct{ capnp.List }

// NewVnObjectAttributeValuePtr creates a new list of VnObjectAttributeValuePtr.
func NewVnObjectAttributeValuePtr_List(s *capnp.Segment, sz int32) (VnObjectAttributeValuePtr_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return VnObjectAttributeValuePtr_List{l}, err
}

func (s VnObjectAttributeValuePtr_List) At(i int) VnObjectAttributeValuePtr {
	return VnObjectAttributeValuePtr{s.List.Struct(i)}
}

func (s VnObjectAttributeValuePtr_List) Set(i int, v VnObjectAttributeValuePtr) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectAttributeValuePtr_List) String() string {
	str, _ := text.MarshalList(0xd5b5408ea84873aa, s.List)
	return str
}

// VnObjectAttributeValuePtr_Promise is a wrapper for a VnObjectAttributeValuePtr promised by a client call.
type VnObjectAttributeValuePtr_Promise struct{ *capnp.Pipeline }

func (p VnObjectAttributeValuePtr_Promise) Struct() (VnObjectAttributeValuePtr, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectAttributeValuePtr{s}, err
}

func (p VnObjectAttributeValuePtr_Promise) Value() ExtAttrValue_Promise {
	return ExtAttrValue_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type VnObjectAttributeValueMap struct{ capnp.Struct }

// VnObjectAttributeValueMap_TypeID is the unique identifier for the type VnObjectAttributeValueMap.
const VnObjectAttributeValueMap_TypeID = 0xf1e4da8ee5d92bf9

func NewVnObjectAttributeValueMap(s *capnp.Segment) (VnObjectAttributeValueMap, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectAttributeValueMap{st}, err
}

func NewRootVnObjectAttributeValueMap(s *capnp.Segment) (VnObjectAttributeValueMap, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VnObjectAttributeValueMap{st}, err
}

func ReadRootVnObjectAttributeValueMap(msg *capnp.Message) (VnObjectAttributeValueMap, error) {
	root, err := msg.RootPtr()
	return VnObjectAttributeValueMap{root.Struct()}, err
}

func (s VnObjectAttributeValueMap) String() string {
	str, _ := text.Marshal(0xf1e4da8ee5d92bf9, s.Struct)
	return str
}

func (s VnObjectAttributeValueMap) Values() (VnObjectAttributeValuePtr_List, error) {
	p, err := s.Struct.Ptr(0)
	return VnObjectAttributeValuePtr_List{List: p.List()}, err
}

func (s VnObjectAttributeValueMap) HasValues() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s VnObjectAttributeValueMap) SetValues(v VnObjectAttributeValuePtr_List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewValues sets the values field to a newly
// allocated VnObjectAttributeValuePtr_List, preferring placement in s's segment.
func (s VnObjectAttributeValueMap) NewValues(n int32) (VnObjectAttributeValuePtr_List, error) {
	l, err := NewVnObjectAttributeValuePtr_List(s.Struct.Segment(), n)
	if err != nil {
		return VnObjectAttributeValuePtr_List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

// VnObjectAttributeValueMap_List is a list of VnObjectAttributeValueMap.
type VnObjectAttributeValueMap_List struct{ capnp.List }

// NewVnObjectAttributeValueMap creates a new list of VnObjectAttributeValueMap.
func NewVnObjectAttributeValueMap_List(s *capnp.Segment, sz int32) (VnObjectAttributeValueMap_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return VnObjectAttributeValueMap_List{l}, err
}

func (s VnObjectAttributeValueMap_List) At(i int) VnObjectAttributeValueMap {
	return VnObjectAttributeValueMap{s.List.Struct(i)}
}

func (s VnObjectAttributeValueMap_List) Set(i int, v VnObjectAttributeValueMap) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectAttributeValueMap_List) String() string {
	str, _ := text.MarshalList(0xf1e4da8ee5d92bf9, s.List)
	return str
}

// VnObjectAttributeValueMap_Promise is a wrapper for a VnObjectAttributeValueMap promised by a client call.
type VnObjectAttributeValueMap_Promise struct{ *capnp.Pipeline }

func (p VnObjectAttributeValueMap_Promise) Struct() (VnObjectAttributeValueMap, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectAttributeValueMap{s}, err
}

const schema_90687959836864ab = "x\xda\x128\xeb\xc0d\xc8Z\xcf\xc2\xc0\x10h\xc2\xca" +
	"\xf6\x7fU\xb1\xc7\x8a>\x87\xadW\x19\x04\x8d\x18\xff\xaf" +
	"N\xc9h\x8e\xac\xcc\x98\xc0\xc0\xca\xc8\xce\xc0`\xac\xca" +
	"\x94\xc4$\xec\xc9\xc4\xce\xc0 \xec\xcad\xcf\xc0\xf8\xff" +
	"\xa7\xf6\xcd\xa7}\xb7\x9e|\xc4\xa68\x15\xa4\xb8\x13\xac" +
	"\xb8\x95\xc9\x9e\xa1\xea\x7frbA^\x81~^>G" +
	"J\xaa~r~nn~\x9e~X\x9e\x7fRVj" +
	"r\x89cIIQfRiIjXbNi\xaa" +
	"ob\x81\x1eX\xb1\x15vy\xf6\x80\x92\xa2\x00F\xc6" +
	"@\x16f\x16\x06\x06\x16F\x06\x06A^#\x06\x86@" +
	"\x0ef\xc6@\x11&F\xf92\x90\x1aF\x81\xff\xa9{" +
	"\xbf\xdf\x91\xfb\xbca6\x03\x03#\xa3\x00\x03#\x15\xed" +
	"\xf7M,@\xb3\xdf\x0aj\xbf\x0a\x13\xa3=\xd8\xfeb" +
	"F>\x06\xc6\x00fFF\x01D\x8820\x82\x04\x01" +
	"\x01\x00\x00\xff\xff\xa5\x07oC"

func init() {
	schemas.Register(schema_90687959836864ab,
		0xd5b5408ea84873aa,
		0xf1e4da8ee5d92bf9)
}
