// Code generated by capnpc-go. DO NOT EDIT.

package vncapnp

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type VnObjectItemsScanCookie struct{ capnp.Struct }

// VnObjectItemsScanCookie_TypeID is the unique identifier for the type VnObjectItemsScanCookie.
const VnObjectItemsScanCookie_TypeID = 0x8402081dabc79360

func NewVnObjectItemsScanCookie(s *capnp.Segment) (VnObjectItemsScanCookie, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return VnObjectItemsScanCookie{st}, err
}

func NewRootVnObjectItemsScanCookie(s *capnp.Segment) (VnObjectItemsScanCookie, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return VnObjectItemsScanCookie{st}, err
}

func ReadRootVnObjectItemsScanCookie(msg *capnp.Message) (VnObjectItemsScanCookie, error) {
	root, err := msg.RootPtr()
	return VnObjectItemsScanCookie{root.Struct()}, err
}

func (s VnObjectItemsScanCookie) String() string {
	str, _ := text.Marshal(0x8402081dabc79360, s.Struct)
	return str
}

func (s VnObjectItemsScanCookie) SliceId() uint16 {
	return s.Struct.Uint16(0)
}

func (s VnObjectItemsScanCookie) SetSliceId(v uint16) {
	s.Struct.SetUint16(0, v)
}

func (s VnObjectItemsScanCookie) InodeNumber() uint32 {
	return s.Struct.Uint32(4)
}

func (s VnObjectItemsScanCookie) SetInodeNumber(v uint32) {
	s.Struct.SetUint32(4, v)
}

func (s VnObjectItemsScanCookie) ClientSliceListPos() uint64 {
	return s.Struct.Uint64(8)
}

func (s VnObjectItemsScanCookie) SetClientSliceListPos(v uint64) {
	s.Struct.SetUint64(8, v)
}

func (s VnObjectItemsScanCookie) ClientSliceListEndPos() uint64 {
	return s.Struct.Uint64(16)
}

func (s VnObjectItemsScanCookie) SetClientSliceListEndPos(v uint64) {
	s.Struct.SetUint64(16, v)
}

// VnObjectItemsScanCookie_List is a list of VnObjectItemsScanCookie.
type VnObjectItemsScanCookie_List struct{ capnp.List }

// NewVnObjectItemsScanCookie creates a new list of VnObjectItemsScanCookie.
func NewVnObjectItemsScanCookie_List(s *capnp.Segment, sz int32) (VnObjectItemsScanCookie_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return VnObjectItemsScanCookie_List{l}, err
}

func (s VnObjectItemsScanCookie_List) At(i int) VnObjectItemsScanCookie {
	return VnObjectItemsScanCookie{s.List.Struct(i)}
}

func (s VnObjectItemsScanCookie_List) Set(i int, v VnObjectItemsScanCookie) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s VnObjectItemsScanCookie_List) String() string {
	str, _ := text.MarshalList(0x8402081dabc79360, s.List)
	return str
}

// VnObjectItemsScanCookie_Promise is a wrapper for a VnObjectItemsScanCookie promised by a client call.
type VnObjectItemsScanCookie_Promise struct{ *capnp.Pipeline }

func (p VnObjectItemsScanCookie_Promise) Struct() (VnObjectItemsScanCookie, error) {
	s, err := p.Pipeline.Struct()
	return VnObjectItemsScanCookie{s}, err
}

const schema_b56ec2d13b48b7cb = "x\xdat\xca1J3A\x1c\x86\xf1\xf7\xfdO\xf2\xed" +
	"\xa6\xcb\x90\xb4\x1fz\x02\xa3\xd8i#\x11\xc1\x80\xc4\x0c" +
	"\x01+\x0b\x93\xd9\x01Gwg\x16w-\x84\x80\x8d\x85" +
	"\xbd\x9d'\x10\xec\x04\xb1\xb7Ia\xe5)<\xc6\x8a6" +
	"6\xda>\xbf\xa7\xfb\xb0#\x1b\xed\xa5\x00f\xb5\xfd\xaf" +
	"9\xb9[>\xfeO\xe5\x06f\x9d\xaay{\xd9\xdf~" +
	"\x7f\x0d\xcfh%\xc0\xe6\x88C\xe9y&@\xcf\xf1\x03" +
	"\xe3\xc6\xce\xcaP\x0eBL37\xb0\xb1(b\x18\x1c" +
	"\x85\xc3\xf9\x99\xb3\xf5\xa8vE5\xb5\xb3\xb0\x1b\xe3\xb9" +
	"wk\xdf\xeb\xd6\x1f\x8a\x09i\xba\xaa\x05\xb4\x08\xe8\xd9" +
	"\x100\xc7\x8a\xe6T\xa8\xc9>\xbf\xa2\x9b\x03&S4" +
	"\xa5P\x0b\xfb\x14@\x17\xf7\x80)\x15\xcdB\xa8\x95\xf4" +
	"\xa9\x00}\xf5\x04\x98\x85\xa2\xb9\x15^W\xb9\xb7n\x94" +
	"1\x810\x01\x1b\x1fb\xe6\xc6\x97\x05\x92\xb9\xbb`\x0a" +
	"a\x0a66\xf7.\xd4\xd3\x9c\xde\xba\x03_\xd5\x13\x15" +
	"+v \xec\xfc\x82{+!\x9b\xfc\xf8g\x00\x00\x00" +
	"\xff\xff\xa0\x99R\x19"

func init() {
	schemas.Register(schema_b56ec2d13b48b7cb,
		0x8402081dabc79360)
}
